### ISSUE TITLE
Issue created about changelog is does not explain how to fix it

### ISSUE THREAD

**Issue by Philip-Scott** [elementary/houston#395] opened 2017-04-04 02:18 UTC
Currently, Houston files this issue if it found a problem with the change log:

```
Apphub had some issues with your changelog. We tried to fix them as best we can,
but you should take a look just in case.
```

It does not explain if it reads the text from the release, or if it's a separate file, or if it has to be on the appinfo file

For context: https://github.com/Philip-Scott/Spice-up/issues/81

**Comment by danrabbit** [comment] 2017-04-08 22:30
From Blake's comment on a relevant bug report:

"Houston grabs the changelog info from the GitHub releases. So the release should have some body text about the changes, aside from the auto generated text from GitHub."

**Comment by luizaugustomm** [comment] 2017-04-10 23:02
I think the message should clarify developers that the issue is related to **Github**'s changelog. When I saw that message for the first time, I thought the issue was in my **debian/changelog**.

**Comment by luizaugustomm** [comment] 2017-04-10 23:04
By the way, do you guys think that there's a way to integrate debian/changelog to github's one?

**Comment by btkostner** [comment] 2017-08-15 21:30
Sadly we can't really use GitHub's release notes anymore because there are no webhooks when it gets updated. So if someone didn't put a body in a release, it will forever stay empty.

Anyway. Closing issue because [it's much better now](https://github.com/elementary/houston/blob/master/src/flightcheck/pipes/Debian/Changelog/warn.md)

**Closed by btkostner** 2017-08-15 21:30 UTC
