### ISSUE TITLE
Error Encountered Processing com.github.ztefn.haguichi.

### ISSUE THREAD

**Issue by ztefn** [elementary/houston#568] opened 2017-12-16 00:20 UTC
As [per request](https://github.com/ztefn/haguichi/issues/3) by one of your users I'm attempting to publish Haguichi to AppCenter. To this end I've created a [separate branch](https://github.com/ztefn/haguichi/tree/elementary) for all elementaryOS specific stuff (AppCenter tags in appdata.xml, no dark theme variant by default, nicely colored headerbar instead, matching screenshots, GitHub RDNN, etc).

After the first push, the dashboard now appears to be stuck in the following error:
_**Error Encountered Processing com.github.ztefn.haguichi.**
This is most likely a problem with this website._

**Comment by btkostner** [comment] 2017-12-16 21:25
So, running the build locally the only error I get is about appstream, which should be fixed with https://github.com/ztefn/haguichi/pull/7. This leads me to think that the error was some function parsing the github release tag. Can you try releasing it under a standard `X.X.X` semver number like `1.3.9`?

Currently there are still two issues with semver in houston. One being parsing some weird semver prerelease values. Second being sorting releases in the database because version is stored as a string instead of three numbers (I know. I'm sorry), which can cause releases with double digit version numbers to be out of order.

**Comment by ztefn** [comment] 2017-12-16 21:49
Releasing it under 1.3.9 means the version for elementaryOS is going to outrun the vanilla version, which is not very desirable. Is there any release tag _between_ 1.3.8 and 1.3.9 that might parse correctly in houston?

**Comment by ztefn** [comment] 2017-12-17 11:43
So I just made a release using the "standard" semver number '0.138.0' and reinstalled AppCenter integration. Same error again after submitting this release.

**Comment by ztefn** [comment] 2017-12-17 14:52
Meanwhile Launchpad has no problem building the elementary branch: https://code.launchpad.net/~ztefn/+recipe/haguichi-elementary

**Comment by btkostner** [comment] 2017-12-17 17:22
It's not the building that is the problem, it's the dashboard sorting release numbers. Give me a day or two and I'll try to track down the last of the sorting issues and fix them in master for you.

**Comment by btkostner** [comment] 2017-12-19 02:08
@ztefn `0.138.0` is less than `1.3.8`, so it would still be trying to build the `1.3.8` version. Did you mean version `1.138.0`?

**Comment by btkostner** [comment] 2017-12-19 02:20
So, I didn't see anything in the server logs, so I copied over the database and changed some of the project values to point to my fork. I re-created a `1.138.0` release `targeting` the elementary branch, then released it on the dashboard. Everything seemed to work as intended except for the expected testing errors (I didn't change any of the code so some of the paths were wrong).

Looking at the database, it seems all of the releases are cleared, so the next release you make should be the first and only one to show in houston.

Let me know if the `1.138.0` release doesn't work for you and I would be happy to look into it some more.

**Closed by btkostner** 2017-12-19 02:20 UTC

**Comment by ztefn** [comment] 2017-12-19 16:45
@btkostner Thanks, I will try that! One question, does the debian/changelog file also need to have that same version, or is that file ignored/generated by houston itself and could therefore be left out completely?

**Comment by btkostner** [comment] 2017-12-19 17:13
The debian changelog will be generated on build from the text you put in the GitHub release body. Sadly GitHub doesn't offer webhooks for when the release text changes, so it will use the text on creation, even if you update it later.

**Comment by ztefn** [comment] 2017-12-20 01:17
Okay, so I submitted 1.138.0. Two new issues were reported by AppCenter bot ([#8](https://github.com/ztefn/haguichi/issues/8) and [#9](https://github.com/ztefn/haguichi/issues/9)).

Fixed them, created and submitted release 1.138.1, now I'm back at this non-descriptive error again...

**Comment by btkostner** [comment] 2017-12-20 15:24
So, it builds and everything should be fine on your end. This is a problem with houston (and mostly nodejs) not being able to recursively delete a folder correctly >:(

I'll fix it tonight and get everything up for review

**Comment by btkostner** [comment] 2017-12-21 01:57
Houston has been updated and you should no longer run into that mysterious error. Currently `1.138.1` is up for review.

**Comment by ztefn** [comment] 2017-12-21 14:01
Thanks! Appears to have passed review already and is now published on AppCenter.
