### ISSUE TITLE
Add option to cancel submissions

### ISSUE THREAD

**Issue by ranfdev** [elementary/houston#728] opened 2019-04-06 19:55 UTC
For example, i've just requested the review of my app, but i've noticed i didn't put any screenshot. I want to cancel the review request and add the screenshots, but there is no option to do it

**Comment by cassidyjames** [comment] 2019-04-06 20:11
@ranfdev creating a new release automatically removes previous releases from the review queue, so that's your best bet. @btkostner I could see a manual override on the submitter's side being helpful as well, though, as long as it's clear they need to submit a *new* release next time.

**Comment by cassidyjames** [comment] 2019-09-18 16:39
This also sounds like a duplicate of #631

**Closed by cassidyjames** 2019-09-18 16:39 UTC
