### ISSUE TITLE
Release .deb packages not recognized as a deb archives.

### ISSUE THREAD

**Issue by michaldaniel** [elementary/houston#467] opened 2017-06-16 00:07 UTC
When downloading any .deb file from GitHub releases of any Houston app, it is not recognized as a deb archive.

Taking for example @danrabbit Harvey application [0.1.3 Harvey release](https://github.com/danrabbit/harvey/releases/download/0.1.4/com.github.danrabbit.harvey_0.1.4_amd64.deb) (but it is same for every [application listed here](https://appstream.elementary.io/appcenter/html/xenial/main/metainfo/index.html)).

If I try to install .deb file with apt:

    $ apt install ./com.github.danrabbit.harvey_0.1.4_amd64.deb
     
      Reading package lists... Error!
      E: Sub-process Popen returned an error code (2)
      E: Encountered a section with no Package: header
      E: Problem with MergeList /home/morningbird/Pobrane/com.github.danrabbit.harvey_0.1.4_amd64.deb
      E: The package lists or status file could not be parsed or opened.

If I try to extract .deb file with ar:

    $  ar vx com.github.danrabbit.harvey_0.1.4_amd64.deb
      
       ar: com.github.danrabbit.harvey_0.1.4_amd64.deb: File format not recognized

If I try to list content with dpkg:

    $  dpkg -c com.github.danrabbit.harvey_0.1.4_amd64.deb 
       
       dpkg-deb: error: 'com.github.danrabbit.harvey_0.1.4_amd64.deb' is not a debian format archive

**Comment by btkostner** [comment] 2017-06-16 00:28
Duplicate of #339

**Comment by btkostner** [comment] 2017-06-16 00:29
Sorry, I meant #399

**Closed by btkostner** 2017-06-16 00:28 UTC
