### ISSUE TITLE
Cannot remove an project from Houston

### ISSUE THREAD

**Issue by cassidyjames** [elementary/houston#223] opened 2016-10-12 15:59 UTC
If I accidentally add a repo not intended for Houston, there's no (at least obvious) way to remove that project from my dashboard.

For example, I have an AppName repo and an AppName.website repo, and accidentally add the AppName.website.

**Comment by danrabbit** [comment] 2016-10-12 18:00
I think this is also going to end up being a dupe of #226

**Closed** 2016-10-13 00:35 UTC
Labels: Subject Houston
